"""Stage 3 — classification of canonical skill sequences with finite automata."""

from resumelens.classification.automata import (
    ALL_PROFILES,
    DATA_PROFILE,
    DEVOPS_PROFILE,
    FULL_STACK_PROFILE,
    ML_PROFILE,
    ProfileSpec,
    Stage,
    accepts,
    accepts_data,
    accepts_devops,
    accepts_full_stack,
    accepts_ml,
    build_automaton,
)
from resumelens.classification.classifier import (
    ACCEPTED,
    PROFILE_SPECS,
    REJECTED,
    ClassificationReport,
    UnknownProfileError,
    classify_all,
    classify_records,
    classify_sequence,
    profile_spec,
    verdict_of,
)

__all__ = [
    "ACCEPTED",
    "ALL_PROFILES",
    "DATA_PROFILE",
    "DEVOPS_PROFILE",
    "FULL_STACK_PROFILE",
    "ML_PROFILE",
    "PROFILE_SPECS",
    "REJECTED",
    "ClassificationReport",
    "ProfileSpec",
    "Stage",
    "UnknownProfileError",
    "accepts",
    "accepts_data",
    "accepts_devops",
    "accepts_full_stack",
    "accepts_ml",
    "build_automaton",
    "classify_all",
    "classify_records",
    "classify_sequence",
    "profile_spec",
    "verdict_of",
]
